# v3 syntax
version: '3'

# Named volumes
volumes:
  # Mysql Data
  inside-mysql-data:
    driver: local

services:
  # PHP (nginx)
  api:
    image: ambientum/php:latest-nginx
    container_name: inside-nginx
    volumes:
      - .:/var/www/app
    ports:
      - "9000:8080"
    links:
      - mysql

  # Mysql (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: inside-mysql
    volumes:
      - inside-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inside
      - MYSQL_USER=inside
      - MYSQL_PASSWORD=secret
